### ISSUE TITLE
DeepSTARR running error

### ISSUE THREAD

**Issue by BenxiaHu** [bernardo-de-almeida/DeepSTARR#1]
Hello,
    Thanks for developping DeepSTARR which is great tool to predict enhancer activity from DNA sequences. I am trying to run DeepSTARR using the following command:
**`python DeepSTARR_new_predict.py -s Sequences_example.fa -m DeepSTARR.model`**
But i got the following error:
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "DeepSTARR_new_predict.py", line 71, in <module>
    keras_model, keras_model_weights, keras_model_json = load_model(model_ID)
  File "DeepSTARR_new_predict.py", line 67, in load_model
    keras_model.load_weights(keras_model_weights)
  File "/nas/longleaf/home/anaconda2/envs/DeepSTARR_gpu/lib/python3.7/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/nas/longleaf/home/anaconda2/envs/DeepSTARR_gpu/lib/python3.7/site-packages/keras/engine/saving.py", line 1004, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

Would you like to tell me how to deal with this issue?
Best,

**Comment by bernardo-de-almeida** [comment]
Thanks for the feedback!
Likely it's because of the h5py version. You can fix it by setting h5py < 3.0.0, e.g. with _pip install 'h5py<3.0.0'_.
